<p>
<font size='5' face='Georgia, Arial'>IIC2233 Apunte Programación Avanzada</font><br>
<font size='1'>&copy; 2024 Francisca Cattan.</font>
<br>
<font size='1'> Modificado 2025-2 por Equipo Docente IIC2233</font>
</p>

# Tabla de contenidos

1. [Introducción a NumPy en Python](#Introducción-a-NumPy-en-Python)
    1. [Importando NumPy](#Importando-NumPy)
2. [Arrays](#Arrays)
    1. [Creación de Arrays](#Creación-de-Arrays)
3. [Funciones de NumPy](#Funciones-de-NumPy)
4. [Operaciones básicas](#Operaciones-básicas)
    1. [Operaciones aritméticas](#Operaciones-aritméticas)
    2. [Operaciones con escalares](#Operaciones-con-escalares)
    3. [Funciones universales](#Funciones-universales)
    4. [Operaciones lógicas y comparaciones](#Operaciones-lógicas-y-comparaciones)
    5. [Indexación y Slicing](#Indexación-y-Slicing)
    6. [Broadcasting](#Broadcasting)
    7. [Concatenación y división](#Concatenación-y-división)
5. [Análisis y estadísticas](#Análisis-y-estadísticas)

# Introducción a NumPy en Python

NumPy es una biblioteca fundamental para el cálculo científico en Python. Proporciona soporte para _arrays_ y matrices multidimensionales, junto con una colección de funciones matemáticas de alto nivel para operar con estos _arrays_ de manera eficiente. En este notebook, exploraremos los usos más comunes de NumPy. Puedes expandir buscando más información en [su documentación](http://www.numpy.org/).

## Importando NumPy
Para utilizar NumPy, primero debemos importarlo. Por convención, se suele importar unsando el alias `np`.

El uso de as `np` es una práctica estándar que crea un alias para la biblioteca. Esto simplifica el código al permitirnos acceder a las funciones y clases de NumPy utilizando el prefijo corto `np` en lugar de `numpy`. Por ejemplo, en lugar de escribir `numpy.array()`, simplemente escribimos `np.array()`. Esta convención no solo hace que el código sea más limpio y fácil de leer, sino que también facilita la colaboración y el intercambio de código, ya que es ampliamente reconocida y utilizada en la comunidad de Python. Además, si estás trabajando con múltiples bibliotecas que tienen funciones con nombres similares, el uso de alias ayuda a evitar conflictos y a mantener el código organizado.

In [1]:
import numpy as np

En caso de que no tengas instalado el módulo, debe correr en la terminal el comando `python3 -m pip install numpy`. Recuerda que si `python3` no funciona, probar con `python`, `py` o `py3`.

# Arrays

**¿Qué es un _array_?**
Un _array_ (o arreglo) es una estructura de datos que almacena una colección de elementos, todos del mismo tipo de dato, en posiciones contiguas de memoria. En el contexto de NumPy, un **array** es una matriz multidimensional que permite realizar operaciones matemáticas y lógicas de manera eficiente y rápida.

**¿Por qué usar _arrays_ de NumPy en lugar de listas de Python?**
Aunque las listas de Python son muy flexibles y pueden contener elementos de diferentes tipos de datos, no están optimizadas para operaciones numéricas y cálculos de alto rendimiento. A continuación, se detallan las ventajas de utilizar _arrays_ de NumPy en comparación a las listas de Python vistas en el curso:
| Característica           | Arrays de NumPy                                                                 | Listas de Python                                                                 |
|---------------------------|---------------------------------------------------------------------------------|----------------------------------------------------------------------------------|
| **Eficiencia en memoria** | Almacenan los datos de manera contigua y homogénea en memoria, reduciendo el consumo de espacio y mejorando la velocidad de acceso. | Almacenan referencias a objetos individuales, lo que aumenta el consumo de memoria, especialmente con grandes conjuntos de datos. |
| **Velocidad de cálculo**  | Las operaciones matemáticas están implementadas en código compilado (generalmente en C), lo que permite realizar cálculos mucho más rápidos. | Las operaciones requieren bucles explícitos en Python, lo que es significativamente más lento. |
| **Operaciones vectorizadas** | Permiten aplicar operaciones a todos los elementos sin necesidad de bucles explícitos. | Requieren iterar manualmente sobre cada elemento. |

A continuación, veremos un ejemplo que calcula la suma de dos listas o _arrays_ de gran tamaño. Para ello contaremos el tiempo de procesamiento usando ambas estructuras de forma comparativa.

In [2]:
import numpy as np
import time

tamano = 1000000

lista_a = list(range(tamano))
lista_b = list(range(tamano))

inicio = time.time()
resultado_lista = [a + b for a, b in zip(lista_a, lista_b)]
fin = time.time()
print("Tiempo con listas de Python:", fin - inicio, "segundos")

array_a = np.arange(tamano)
array_b = np.arange(tamano)

inicio = time.time()
resultado_array = array_a + array_b
fin = time.time()
print("Tiempo con arrays de NumPy:", fin - inicio, "segundos")

Tiempo con listas de Python: 0.05272054672241211 segundos
Tiempo con arrays de NumPy: 0.0023980140686035156 segundos


## Creación de Arrays

Podemos crear un _array_ de NumPy a partir de una **lista** o **tupla** de Python utilizando la función `np.array()`. Esta función toma como entrada un objeto que se puede iterar (como una lista o tupla) y devuelve un _array_ de NumPy que contiene los mismos elementos. Esto es especialmente útil para convertir datos existentes en estructuras más eficientes para cálculos numéricos.

In [3]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print("Array creado a partir de una lista:", array)

Array creado a partir de una lista: [1 2 3 4 5]


A continuación veremos otro ejemplo, pero creando un _array_ a partir de una tupla.

In [4]:
tupla = (10, 20, 30, 40, 50)
array = np.array(tupla)
print("Array creado a partir de una tupla:", array)

Array creado a partir de una tupla: [10 20 30 40 50]


Algo importante a notar es que al crear un _array_, NumPy intenta inferir el tipo de datos (`dtype`) más adecuado según los elementos proporcionados. Si todos los elementos son enteros, el _array_ tendrá tipo entero; si hay flotantes, el _array_ será de tipo flotante.

In [5]:
lista_mixta = [1, 2.5, 3, 4.75]
array_mixto = np.array(lista_mixta)
print("Array con tipos mixtos:", array_mixto)
print("Tipo de datos del array:", array_mixto.dtype)

Array con tipos mixtos: [1.   2.5  3.   4.75]
Tipo de datos del array: float64


Podríamos, si quisiéramos, controlar el tipo de datos del _array_ resultante, puedes utilizar el parámetro `dtype` en la función `np.array()`.

In [6]:
lista_enteros = [1, 2, 3, 4, 5]
array_float = np.array(lista_enteros, dtype=float)
print("Array con tipo de datos float:", array_float)
print("Tipo de datos del array:", array_float.dtype)

Array con tipo de datos float: [1. 2. 3. 4. 5.]
Tipo de datos del array: float64


También podemos crear _arrays_ multidimensionales anidando listas o tuplas. En este caso lo utilizaremos para simular una matriz desde una **lista de listas**.

In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


# Funciones de NumPy
NumPy ofrece varias funciones para crear _arrays_ de manera eficiente.
- `np.arange()`: Similar a `range()`, pero devuelve un _array_.
- `np.linspace()`: Genera números equiespaciados en un intervalo.
- `np.zeros()` y `np.ones()`: Crea _arrays_ de ceros o unos.
- `np.eye()`: Crea una matriz identidad.
- `np.random`: Genera _arrays_ con números aleatorios.

In [8]:
array = np.arange(0, 10, 2)
print(array)

[0 2 4 6 8]


In [9]:
array = np.linspace(0, 1, 5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
aleatorios = np.random.rand(5)
print(aleatorios)

[0.54974014 0.8672938  0.85799574 0.25860653 0.8141549 ]


# Operaciones básicas
NumPy permite realizar operaciones matemáticas y lógicas sobre _arrays_ de manera eficiente y sencilla. Estas operaciones pueden ser elemento por elemento o involucrar operaciones matriciales más complejas.

## Operaciones aritméticas

Las operaciones aritméticas básicas en NumPy se aplican elemento por elemento, lo que significa que la operación se realiza entre elementos correspondientes de los _arrays_. Eso si, es importante considerar que los _arrays_ involucrados en a operación deben tener la misma forma (*shape*).

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)
print("Potencia:", a ** 2)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]
Potencia: [1 4 9]


## Operaciones con escalares
Puedes realizar operaciones entre un _array_ y un escalar (un solo número). En este caso, el escalar se aplica a cada elemento del _array_.

In [14]:
a = np.array([1, 2, 3])

print("Suma con escalar:", a + 10)
print("Multiplicación con escalar:", a * 3)

Suma con escalar: [11 12 13]
Multiplicación con escalar: [3 6 9]


## Funciones universales
Las funciones universales de NumPy son funciones que se aplican elemento por elemento sobre _arrays_. Incluyen funciones matemáticas como seno, coseno, logaritmo, exponencial, entre otras.

In [15]:
array = np.array([0, np.pi/2, np.pi])

print("Seno:", np.sin(array))
print("Coseno:", np.cos(array))
print("Exponencial:", np.exp(array))
print("Logaritmo:", np.log(array + 1))  # para evitar log(0) D:

Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponencial: [ 1.          4.81047738 23.14069263]
Logaritmo: [0.         0.94421571 1.42108041]


## Operaciones lógicas y comparaciones
NumPy permite realizar operaciones lógicas y comparaciones entre _arrays_. Algo interesante es que estas operaciones retornan _arrays_ booleanos, como observaremos en el siguiente ejemplo.

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print("Igualdad:", a == b)
print("Mayor que:", a > b)
print("Menor o igual que:", a <= b)
print("Condición lógica:", (a > 2) & (b < 3)) # se usa & y |

Igualdad: [False False False False]
Mayor que: [False False  True  True]
Menor o igual que: [ True  True False False]
Condición lógica: [False False  True  True]


## Indexación y Slicing
La indexación y el _slicing_ en NumPy permiten acceder y modificar elementos o subconjuntos de un _array_.

In [17]:
array = np.array([10, 20, 30, 40, 50])

print("Elemento en posición 0:", array[0])
print("Último elemento:", array[-1])
print("Slice de 1 a 3:", array[1:4])

array[0] = 100
print("Array modificado:", array)

Elemento en posición 0: 10
Último elemento: 50
Slice de 1 a 3: [20 30 40]
Array modificado: [100  20  30  40  50]


¿Y qué ocurre en _arrays_ multidimensionales? Es importante en este caso especificar índices para cada dimensión. Puedes utilizar el slicing (`:`) para seleccionar rangos de índices.

In [18]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print("Elemento en fila 0, columna 1:", matriz[0, 1])
print("Primera fila:", matriz[0, :])
print("Tercera columna:", matriz[:, 2])
print("Suma por columnas:", np.sum(matriz, axis=0))
print("Suma por filas:", np.sum(matriz, axis=1))

Elemento en fila 0, columna 1: 2
Primera fila: [1 2 3]
Tercera columna: [3 6]
Suma por columnas: [5 7 9]
Suma por filas: [ 6 15]


## Broadcasting
El _broadcasting_ es una poderosa característica de NumPy que permite realizar operaciones entre _arrays_ de diferentes dimensiones y formas, siempre que sean compatibles.

In [19]:
a = np.array([1, 2, 3])
matriz = np.array([[10], [20], [30]])

print("Resultado del broadcasting:\n", matriz + a)

Resultado del broadcasting:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


En este ejemplo, el _array_ `a` se expande para que coincida con la forma de `matriz`.

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
matriz = np.array([[10], [20]])

print("Resultado del broadcasting:\n", a + matriz) # el orden no afecta

Resultado del broadcasting:
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]]


## Concatenación y división

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenado = np.concatenate((a, b))
print("Arrays concatenados:", concatenado)

Arrays concatenados: [1 2 3 4 5 6]


In [22]:
array = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(array, 3)
print("Arrays divididos:", split_arrays)

Arrays divididos: [array([1, 2]), array([3, 4]), array([5, 6])]


# Análisis y estadísticas
NumPy también proporciona funciones para calcular estadísticas básicas. Estas pueden aplicarse a _arrays_ multidimensionales, especificando el eje (`axis`) sobre el cual realizar el cálculo.

In [23]:
array = np.array([1, 2, 3, 4, 5])

print("Suma:", np.sum(array))
print("Media:", np.mean(array))
print("Mediana:", np.median(array))
print("Desviación estándar:", np.std(array))
print("Varianza:", np.var(array))
print("Valor máximo:", np.max(array))
print("Valor mínimo:", np.min(array))
print("Índice del valor máximo:", np.argmax(array))

Suma: 15
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Valor máximo: 5
Valor mínimo: 1
Índice del valor máximo: 4


Te invitamos a conocer otras potencialidades de NumPy. Entre las muchas posibilidades, puedes realizar cálculos de Álgebra Lineal como:
- Producto punto
- Multiplicación de matrices
- Transpuesta de una matriz
- Determinante y matriz inversa
- Valores y vectores propios
- Descomposición en Valores Singulares (SVD)

Para consolidar estos conocimientos, recomendamos practicar con ejemplos y ejercicios que apliquen estas operaciones en contextos reales. Puedes iniciar con el procesamiento de datos que te interesen, o resolver sistemas de ecuaciones y aplicar análisis estadístico.